items:
  BREAK_WOODEN_SWORD:
    name: "§7Сломанный деревянный меч"
    material: WOODEN_SWORD
    PHYSICAL_DAMAGE: 10
    CRITICAL_CHANGE: 20
    MOVESPEED: -5.0
    change: 80
  NORMAL_WOODEN_SWORD:
    name: "§fОбычный деревянный меч"
    material: WOODEN_SWORD
    PHYSICAL_DAMAGE: 10
    CRITICAL_CHANGE: 20
    MOVESPEED: -5.0
    change: 60
  RARE_WOODEN_SWORD:
    name: "§bРедкий деревянный меч"
    material: WOODEN_SWORD
    PHYSICAL_DAMAGE: 10
    CRITICAL_CHANGE: 20
    MOVESPEED: -5.0
    change: 30
  MYTHICAL_WOODEN_SWORD:
    name: "§dМифический деревянный меч"
    material: WOODEN_SWORD
    PHYSICAL_DAMAGE: 10
    CRITICAL_CHANGE: 20
    MOVESPEED: -5.0
    change: 5
  LEGENDARY_WOODEN_SWORD:
    name: "§eЛегендарный деревянный меч"
    material: WOODEN_SWORD
    PHYSICAL_DAMAGE: 10
    CRITICAL_CHANGE: 20
    MOVESPEED: -5.0
    change: 1